### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 2044-space-elevator** [kfy666/CppCodeTemplate#6]
- [x] 统一索引和算法分类同步，比如：

```
- 基础
    - [A+B]()
……
```

- [ ] 不要以标准输入输出形式书写代码，而是以函数输入输出。
- [x]  进行算法分类，比如图论算法放图论文件夹内，数论算法放数论文件夹内。

**Comment by 2044-space-elevator** [comment]
@kfy666 

在更换标准输入输出形式上，工程量会很大。

不过这样的好处是可以用头文件的形式来引用此项目代码。

**Comment by kfy666** [comment]
@2044-space-elevator
感谢您提的建议，能否麻烦您叙述一下每个建议的具体内容。本人是高一OIer，有一些不是很懂 :D

**Comment by 2044-space-elevator** [comment]
> @2044-space-elevator 感谢您提的建议，能否麻烦您叙述一下每个建议的具体内容。本人是高一OIer，有一些不是很懂 :D

第一个是说将算法分类也放入索引当中，就比如说，Math 就这样写：

- Math
    - [Chinese-remainder-theorem.cpp](https://github.com/kfy666/CppCodeTemplate/blob/main/Templates/Math/Chinese-remainder-theorem.cpp)
    - [Prime-Euler-sieve.cpp](https://github.com/kfy666/CppCodeTemplate/blob/main/Templates/Math/Prime-Euler-sieve.cpp)

第二个有一个子项，就是说当使用函数形式来书写代码时，可以像头文件一样引用 Templates 里的项目，比如……

```cpp
#include "Templates/Math/Prime-Euler-sieve.h"
```

但是最好把 Templates 里的代码都换成 `.h` 后缀的。

**Comment by 2044-space-elevator** [comment]
> @2044-space-elevator 感谢您提的建议，能否麻烦您叙述一下每个建议的具体内容。本人是高一OIer，有一些不是很懂 :D

意思是说，比如，有以下代码：

```cpp
int main() {
    int a, b; cin >> a >> b; cout << exgcd(a, b);
}
```

这时候只保留 `exgcd`，就是说允许外部用函数调用的形式直接使用本模板，不过要求就是所有 `.cpp` 得改成 `.h`。

**Comment by kfy666** [comment]
这个的话，因为代码是面向OI选手的，目的就是让选手了解整个代码流程，而不是简单地去调用函数，所以应该会保留输入输出和<code>.cpp</code>

**Comment by 2044-space-elevator** [comment]
> > > @2044-space-elevator 感谢您提的建议，能否麻烦您叙述一下每个建议的具体内容。本人是高一OIer，有一些不是很懂 :D
> > 
> > 
> > 意思是说，比如，有以下代码：
> > ```c++
> > int main() {
> >     int a, b; cin >> a >> b; cout << exgcd(a, b);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这时候只保留 `exgcd`，就是说允许外部用函数调用的形式直接使用本模板，不过要求就是所有 `.cpp` 得改成 `.h`。
> 
> 这个的话，因为代码是面向OI选手的，目的就是让选手了解整个代码流程，而不是简单地去调用函数，所以应该会保留输入输出和`.cpp`

部分支持您的观点，我认为还是删除标准输入输出部分，只保留模板的主体框架：毕竟不同题目的输入方式不同，OI-wiki 也是采用的这种方式。

**Comment by kfy666** [comment]
> Reference

打算把main函数内的写成注释，大致叙述模板的功能及使用

**Comment by 2044-space-elevator** [comment]
> 打算把main函数内的写成注释，大致叙述模板的功能及使用

那其实还不如把 main 函数取消注释罢……

其实我觉得最好是这样，比如有些代码不是要求输入一个数组之类的么？好，那么就将函数参数设为数组，或者说（几乎）删除所有局部变量，只展示函数部分。

> 另外我有事，有消息明天回复。

**Comment by kfy666** [comment]
去掉了一些带有明显题目局限性的输入输出，但保留了一部分输入必要数据如连边（图论），数组（排序）。

**Comment by 2044-space-elevator** [comment]
> 去掉了一些带有明显题目局限性的输入输出，但保留了一部分输入必要数据如连边（图论），数组（排序）。

我觉得差不多了，这个提案就这样干掉吧。
